### PR TITLE
Updates For Static Issue

### PR DESCRIPTION
**Pull request by darrenw2112**
---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#224: Bug: Static noise appears over a long period of audio processing](https://issuehunt.io/repos/98095061/issues/224)
---
</details>

### CODE REVIEW

**Comment by nodeful** [comment]
Can you please reindent those two files with just 2 spaces? This project uses 2 space indentation format. Then I can merge in and release a test version for people :)

**Comment by darrenw2112** [comment]
Done and pushed to my fork.Do I need to create another pull request?
    On Wednesday, June 24, 2020, 01:36:51 PM EDT, Roman Kisil <notifications@github.com> wrote:  
 
 


Can you please reindent those two files with just 2 spaces? This project uses 2 space indentation format. Then I can merge in and release a test version for people :)

**Comment by nodeful** [comment]
No I will sort everything out from here. Thank you. I will merge it into development for now and release a test build shortly

**Comment by nodeful** [comment]
Once people approve the issue is fixed I will transfer the IssueHunt bounty to you

**Comment by nodeful** [comment]
I somehow fucked up the merge trying to fix the indentations for you initially :( Will have to figure it out

**Comment by darrenw2112** [comment]
I always just use the default Xcode 4 space.  I just changed it to 2, reformatted, and checked it in again.

**Pull request merged**
