### PR TITLE
Fix for output change crashes

### PR DESCRIPTION
**Pull request by e5faf2**
Fixed couple of crashes related to force unwrap of optional Driver.device when output chages like on/off bluetooth headphones in native part.

Crash 1:
crash 1 - Volume swift

Crash 2:
crash 2 - Application swift 2020-10-31 12-10-42

### CODE REVIEW

**Comment by nodeful** [comment]
So do you mean that the Driver device is not accessible when BT headphones are being turned on or off? How does that happen? I forcefully unwrapped the driver device because the app shouldn't even run without it 🤔

**Comment by e5faf2** [comment]
Forced unwrap of optionals cause crashes, when optional is `nil`. Especially it could happen for resources like audio devices. It looks like `setupDriverDeviceEvents` method called not at right time and device is not initialized during the call. 

We can see delays (100ms and 500ms) before `setupDriverDeviceEvents` call. Seems it is not enough to process output change correctly.
I think suggested PR can help to avoid some crashes for output change case. At least for native code base part.

**Comment by nodeful** [comment]
Ok I will look into it more thoroughly and see if your implementation of the fix is the right one :) Thanks for looking into it. I really appreciate it!

**Comment by e5faf2** [comment]
FYI: The above crashes could be reproduced by different volume gain level in the app for internal speakers and bt headphones, and by switching between these outputs by in-app dropdown.

image

image

**Pull request closed without merging**
